<?php
use Migrations\AbstractSeed;

/**
 * WorkflowSteps seed.
 */
class WorkflowStepsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '1',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-10-25 12:10:14',
            ],
            [
                'id' => '2',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '1',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:52:52',
                'created_user_id' => '1',
                'created' => '2015-10-25 12:10:14',
            ],
            [
                'id' => '3',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '1',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:52:38',
                'created_user_id' => '1',
                'created' => '2015-10-25 12:10:14',
            ],
            [
                'id' => '4',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '2',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '5',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '2',
                'modified_user_id' => '2',
                'modified' => '2017-11-03 09:24:56',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '6',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '2',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '7',
                'name' => 'Pending For Recommendation',
                'category' => '0',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '2',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '8',
                'name' => 'Pending For Accreditation',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '2',
                'modified_user_id' => '2',
                'modified' => '2017-11-03 09:27:05',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '9',
                'name' => 'Accredited',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '2',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 14:10:02',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '10',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '3',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '11',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '3',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:53:31',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '12',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '3',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '13',
                'name' => 'Pending For Recommendation',
                'category' => '0',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '3',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '14',
                'name' => 'Pending For Registration',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '3',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 14:18:47',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '15',
                'name' => 'Registered',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '3',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 14:21:01',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '16',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '4',
                'modified_user_id' => '2',
                'modified' => '2017-10-20 09:50:15',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '17',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '4',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:53:45',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '18',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '4',
                'modified_user_id' => '2',
                'modified' => '2017-10-20 09:50:21',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '19',
                'name' => 'Pending For Evaluation',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '4',
                'modified_user_id' => '2',
                'modified' => '2017-10-20 09:53:55',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '20',
                'name' => 'Pending For Posting',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '4',
                'modified_user_id' => '2',
                'modified' => '2017-10-20 09:49:32',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '21',
                'name' => 'Posted',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '4',
                'modified_user_id' => '2',
                'modified' => '2017-10-20 09:49:40',
                'created_user_id' => '1',
                'created' => '2015-11-06 11:27:06',
            ],
            [
                'id' => '22',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '5',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-12-15 15:41:56',
            ],
            [
                'id' => '23',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '5',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:54:00',
                'created_user_id' => '1',
                'created' => '2015-12-15 15:41:56',
            ],
            [
                'id' => '24',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '5',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-12-15 15:41:56',
            ],
            [
                'id' => '25',
                'name' => 'Approved',
                'category' => '0',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '5',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2015-12-15 15:41:56',
            ],
            [
                'id' => '26',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '6',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-02-12 18:29:36',
            ],
            [
                'id' => '27',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '6',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:02:28',
                'created_user_id' => '1',
                'created' => '2016-02-12 18:29:36',
            ],
            [
                'id' => '28',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '6',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:02:49',
                'created_user_id' => '1',
                'created' => '2016-02-12 18:29:36',
            ],
            [
                'id' => '29',
                'name' => 'Active',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '6',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:02:59',
                'created_user_id' => '1',
                'created' => '2016-02-12 18:29:36',
            ],
            [
                'id' => '30',
                'name' => 'Pending For Deactivation',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '0',
                'workflow_id' => '6',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:03:08',
                'created_user_id' => '1',
                'created' => '2016-02-12 18:29:36',
            ],
            [
                'id' => '31',
                'name' => 'Inactive',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '6',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:03:16',
                'created_user_id' => '1',
                'created' => '2016-02-12 18:29:36',
            ],
            [
                'id' => '32',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '7',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:01:34',
                'created_user_id' => '1',
                'created' => '2016-04-15 10:45:45',
            ],
            [
                'id' => '33',
                'name' => 'Pending Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '7',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:54:43',
                'created_user_id' => '1',
                'created' => '2016-04-15 10:45:45',
            ],
            [
                'id' => '34',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '7',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:02:02',
                'created_user_id' => '1',
                'created' => '2016-04-15 10:45:45',
            ],
            [
                'id' => '35',
                'name' => 'Approved',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '7',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:02:11',
                'created_user_id' => '1',
                'created' => '2016-04-15 10:45:45',
            ],
            [
                'id' => '36',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '0',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '8',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:04',
            ],
            [
                'id' => '37',
                'name' => 'Pending For Review',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '8',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:56:00',
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:04',
            ],
            [
                'id' => '38',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '8',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:56:14',
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:04',
            ],
            [
                'id' => '39',
                'name' => 'Withdrawn',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '8',
                'modified_user_id' => '1',
                'modified' => '2016-11-10 17:36:39',
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:04',
            ],
            [
                'id' => '40',
                'name' => 'Approved',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '8',
                'modified_user_id' => '1',
                'modified' => '2016-11-10 17:31:36',
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:04',
            ],
            [
                'id' => '41',
                'name' => 'Rejected',
                'category' => '0',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '8',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:04',
            ],
            [
                'id' => '42',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '9',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:05',
            ],
            [
                'id' => '43',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '9',
                'modified_user_id' => '2',
                'modified' => '2016-11-10 13:55:00',
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:05',
            ],
            [
                'id' => '44',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '9',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2016-11-08 07:25:05',
            ],
            [
                'id' => '45',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '10',
                'modified_user_id' => '2',
                'modified' => '2017-10-13 16:15:07',
                'created_user_id' => '2',
                'created' => '2016-11-16 16:12:09',
            ],
            [
                'id' => '46',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '10',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 11:37:51',
                'created_user_id' => '2',
                'created' => '2016-11-16 16:12:09',
            ],
            [
                'id' => '47',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '10',
                'modified_user_id' => '2',
                'modified' => '2016-11-16 16:12:09',
                'created_user_id' => '2',
                'created' => '2016-11-16 16:12:09',
            ],
            [
                'id' => '48',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '11',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-03-10 07:14:53',
            ],
            [
                'id' => '49',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '11',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:01:10',
                'created_user_id' => '1',
                'created' => '2017-03-10 07:14:53',
            ],
            [
                'id' => '50',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '11',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-03-10 07:14:53',
            ],
            [
                'id' => '51',
                'name' => 'Active',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '11',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:01:18',
                'created_user_id' => '1',
                'created' => '2017-03-10 07:14:53',
            ],
            [
                'id' => '62',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '13',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-04-10 09:55:37',
            ],
            [
                'id' => '63',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '13',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-04-10 09:55:37',
            ],
            [
                'id' => '64',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '13',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-04-10 09:55:37',
            ],
            [
                'id' => '65',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '14',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:04:06',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:44:47',
            ],
            [
                'id' => '66',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '14',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 10:03:54',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:44:47',
            ],
            [
                'id' => '67',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '14',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 11:38:44',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:44:47',
            ],
            [
                'id' => '68',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '15',
                'modified_user_id' => '2',
                'modified' => '2017-10-13 14:59:36',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:58:28',
            ],
            [
                'id' => '69',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '15',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 11:37:28',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:58:28',
            ],
            [
                'id' => '70',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '15',
                'modified_user_id' => '2',
                'modified' => '2017-10-13 14:58:28',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:58:28',
            ],
            [
                'id' => '71',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '16',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 11:36:20',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:59:03',
            ],
            [
                'id' => '72',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '16',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 11:39:10',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:59:03',
            ],
            [
                'id' => '73',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '16',
                'modified_user_id' => '2',
                'modified' => '2017-10-13 14:59:03',
                'created_user_id' => '2',
                'created' => '2017-10-13 14:59:03',
            ],
            [
                'id' => '74',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '17',
                'modified_user_id' => '8',
                'modified' => '2017-10-13 15:32:19',
                'created_user_id' => '8',
                'created' => '2017-10-13 15:32:19',
            ],
            [
                'id' => '75',
                'name' => 'Pending For Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '17',
                'modified_user_id' => '1',
                'modified' => '2017-12-21 11:37:07',
                'created_user_id' => '8',
                'created' => '2017-10-13 15:32:19',
            ],
            [
                'id' => '76',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '17',
                'modified_user_id' => '8',
                'modified' => '2017-10-13 15:32:19',
                'created_user_id' => '8',
                'created' => '2017-10-13 15:32:19',
            ],
            [
                'id' => '79',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '18',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '80',
                'name' => 'Pending Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '18',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '81',
                'name' => 'Pending Approval From Sending Institution',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '18',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '82',
                'name' => 'Pending Staff Assignment',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '18',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '83',
                'name' => 'Assigned',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '18',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '84',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '18',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '85',
                'name' => 'Open',
                'category' => '1',
                'is_editable' => '1',
                'is_removable' => '1',
                'is_system_defined' => '1',
                'workflow_id' => '19',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '86',
                'name' => 'Pending Approval',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '19',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '87',
                'name' => 'Pending Approval From Receiving Institution',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '19',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '88',
                'name' => 'Pending Staff Transfer',
                'category' => '2',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '19',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '89',
                'name' => 'Transferred',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '0',
                'workflow_id' => '19',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
            [
                'id' => '90',
                'name' => 'Closed',
                'category' => '3',
                'is_editable' => '0',
                'is_removable' => '0',
                'is_system_defined' => '1',
                'workflow_id' => '19',
                'modified_user_id' => NULL,
                'modified' => NULL,
                'created_user_id' => '1',
                'created' => '2017-11-15 14:51:18',
            ],
        ];

        $table = $this->table('workflow_steps');
        $table->insert($data)->save();
    }
}
